version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lazyshell
    main: ./cmd/lazyshell
    binary: lazyshell
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/thomas-gleizes/lazyshell/pkg/version.Version={{.Version}}

archives:
  - id: lazyshell
    ids:
      - lazyshell
    name_template: "lazyshell_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
